### PR TITLE
Create pandather.yaml

### PR DESCRIPTION
**Pull request by pandather**
add my repo to the list

### CODE REVIEW

**Comment by pandather** [comment]
IK I'm not a well known dev, but I have several other tweaks I plan on releasing once I get my Silica repo working how I expect/want it to. I got a decent bit of positive feedback for just this tweak over at https://www.reddit.com/r/jailbreak/comments/vfptl4/free_release_danktime_ever_use_24hr_time_but_wish/

I just wanted to comment this as I saw other repos have had their initial pull requests closed as the maintainers had never heard of the repo that was requested to be added.

**Comment by ja1dan** [comment]
Hi there!

Thanks for leaving a comment providing one of your works - feedback looks good enough to put the repo on Canister, so that's a good thing!

From your comment, it looks like the repo isn't up yet; I don't think it'd be much use to put a repo that doesn't work onto Canister just yet. I'll leave the PR open, and if you could leave another comment when the repo is up, I'll merge it. Thanks!

**Comment by pandather** [comment]
The repo is up, functional, but only has 1 simple package at the moment! I was just saying more will come soon. :)

**Comment by pandather** [comment]
I just will be adding more packages as I take screenshots and make depictions.

**Comment by ja1dan** [comment]
Alright, I guess i'll go ahead and merge then.

**Pull request merged**
