### PR TITLE
Remove mrmadjb.github.io from piracy list

### PR DESCRIPTION
**Pull request by asdfugil**
This repository never contained piracy, and does not seem to be dangerous.
Package analysis:
`com.mrmadjb.*cht`: Locale files (`/Library/PreferenceBundles/*.bundle/zh-Hant-TW.lproj`) for some tweaks. Does not actually contain the tweaks.

`com.mrmadjb.PxMartPRO`: Appears to be a jailbreak detection bypass. Google Search suggested that this is (one of) the original hosting repo. ([Website of developer](https://s2339956.github.io/about/) links to a post of the blog of this repo)
This link on the site:
> 越獄插件 - 完美繞過全聯 PX Pay 越獄偵測機制，讓你完美使用全聯App

`com.mrmadjb.esunbankbypass`: Also appears to be a jailbreak detection bypass. Google Search suggested that this is (one of) the original hosting repo. (Every search result links to this repo if linked a repo at all + proper credits + presumption of innocence)

no idea why it is added in the first place.

### CODE REVIEW

**Comment by ja1dan** [comment]
image

looks like piracy to me, sorry

**Comment by asdfugil** [comment]
> image
> 
> looks like piracy to me, sorry

 it only contains locale files, not callbar xs itself

**Comment by asdfugil** [comment]
please actually read the package analysis

**Comment by asdfugil** [comment]
Doesn’t look like piracy to me

```
nick@nick-pc [0]:~$ dpkg-deb -c com.mrmadjb.callbarxscht_2.1-35_iphoneos-arm.deb
drwxrwxr-x mrmad/staff       0 2019-03-12 22:47 ./
drwxr-xr-x mrmad/staff       0 2019-03-12 22:47 ./Library/
drwxr-xr-x mrmad/staff       0 2019-03-12 22:39 ./Library/PreferenceBundles/
drwxr-xr-x mrmad/staff       0 2019-03-12 22:32 ./Library/PreferenceBundles/CallBarXPreferences.bundle/
drwx------ mrmad/staff       0 2019-03-12 22:24 ./Library/PreferenceBundles/CallBarXPreferences.bundle/zh-Hant-TW.lproj/
-rw-r--r-- mrmad/staff     230 2019-03-07 22:20 ./Library/PreferenceBundles/CallBarXPreferences.bundle/zh-Hant-TW.lproj/CallBarXActivations.strings
-rw-r--r-- mrmad/staff    2142 2019-03-07 23:50 ./Library/PreferenceBundles/CallBarXPreferences.bundle/zh-Hant-TW.lproj/CallBarXPreferences.strings
-rw-r--r-- mrmad/staff     155 2019-03-07 22:42 ./Library/PreferenceBundles/CallBarXPreferences.bundle/zh-Hant-TW.lproj/CallBarXSColors.strings
```

**Pull request merged**
