### PR TITLE
chore: index zeusteam.dev / Zeus/Electric repo

### PR DESCRIPTION
**Pull request by r1sk01**
(Drama has subsided via email)

### CODE REVIEW

**Comment by tale** [comment]
Is Zeus a bootstrap repository?

**Comment by r1sk01** [comment]
> Is Zeus a bootstrap repository?

Not yet, when it is, I will modify it to say so

**Comment by elihwyma** [comment]
@WillXProject can I just ask what the purpose of this repository is?

**Comment by tale** [comment]
We'll keep this PR open until you finish implementing the repository. I don't see any point in adding it now only to change it later. You also need to remember that repositories marked with `bootstrap: true` are excluded from search results in Sileo.

**Comment by r1sk01** [comment]
after talking with the team, the repo will not be bootstrapped otherwise known as installer-only, it is planned to be public

**Comment by tale** [comment]
For Canister the `bootstrap` flag means that the vendor hosts system packages that can break installations (ie. different versions of APT, tweak injectors, etc). You'll need to tell us if your repository hosts packages that fit that description.

**Comment by r1sk01** [comment]
> For Canister the `bootstrap` flag means that the vendor hosts system packages that can break installations (ie. different versions of APT, tweak injectors, etc). You'll need to tell us if your repository hosts packages that fit that description.

It does not fit that flag, we are not planning to get into that flag anytime soon either

**Pull request merged**
