### PR TITLE
Zeus is not a piracy repo

### PR DESCRIPTION
**Pull request by ariezinc**
Like come on azreal gets everything free? they didnt even leave a description and they got merged fix your piracy list.

thanks,
ariez @ ariez.codes

### CODE REVIEW

**Comment by RidgewayPlus** [comment]
so true bestie slay

**Comment by itsnebulalol** [comment]
This repo has numerous rehosted packages and at one point was a copy of BigBoss 💀

**Comment by tale** [comment]
@ariezinc you've been blocked from the GitHub organization for now.

Please resolve the issues privately and refrain from using GitHub as your place to cause drama and create annoyance. There are many members of the organization that get emails every time you create a pull request and you've been doing it as spam. Once you've resolved whatever issue it is that you have with whomever, please email [support@canister.me](mailto:support@canister.me).

*(Be warned that if you spam the support-email, I'll have no choice but to block you as a sender)*

**Comment by WillXProject** [comment]
Hello, I am the owner of Zeus repo and confirm that this is true by looking at pull request #58
I have attempted to pull this across and was promptly ignored, including receiving multiple threats after sending the request by azreal

**Comment by tale** [comment]
@WillXProject please refer to the message I sent above. Feel free to send an email once you have resolved whatever issue it is between yourself and other groups. Stop dragging a completely unrelated service into your drama. If you create spam pull requests, I'm also left with no choice other than to block you from the GitHub organization.

**Pull request closed without merging**
