### PR TITLE
chore: remove zeusteam.dev from piracy, add to repo list (we aren't a piracy repo) and add Ironside to piracy list (piracy repo, hosting tweaks they aren't allowed to)

### PR DESCRIPTION
**Pull request by r1sk01**
Azreal was the one to initially make the request to add our repo to the piracy list, for some background info, Azreal has harassed me and the Zeus team, even including sending false bans to major Discord servers such as the following:
Plooshi's hub (friends server)
Palera1n
r/Jailbreak
Enmity
Sileo
This is blatantly an attempt at assassinating the Zeus/Electric repo as their personal repo is dying and they take the blame out on us
They also have decided to intentionally host tweaks which either have a license which they are violating or they don't have sufficient permission to host

### CODE REVIEW

**Comment by azaz0322** [comment]
would love to see the tweaks i'm not allowed to host, unlike yall

**Comment by r1sk01** [comment]
> would love to see the tweaks i'm not allowed to host, unlike yall

it's so obvious, if I got $1 every time that you harassed us and decided to fuck with our repo, I'd be a millionaire

**Comment by azaz0322** [comment]
love how you just avoid the subject instead of actually telling me since this is completely false

**Comment by kirb** [comment]
Numerous people receive emails for each message posted in this thread. Please sort this out amongst yourselves elsewhere, this seems to be a personal dispute that Canister needs no part in.

**Comment by ja1dan** [comment]
Until I see concrete proof and evidence of Ironside hosting packages that they aren't allowed to, I'm closing this issue.

**Pull request closed without merging**
